// ── Types ─────────────────────────────────────────────────────────────────────
export type {
  SquadName,
  SkillName,
  AgentMeta,
  ModelTier,
  AgentConfig,
  Priority,
  TaskStatus,
  TaskInput,
  TaskOutput,
  TaskNext,
  TaskFrom,
  Task,
  TaskFilter,
  ReviewVerdict,
  FindingSeverity,
  ReviewFinding,
  RevisionPriority,
  RevisionRequest,
  Review,
  PipelineStep,
  PipelineStatus,
  PipelineTrigger,
  PipelineDefinition,
  PipelineRun,
  EventType,
  SystemEvent,
  ScheduleEntry,
  SystemState,
  DegradationLevel,
  ComponentStatus,
  ComponentHealth,
  SystemHealth,
  WorkspaceDir,
  WorkspaceConfig,
  WorkspacePaths,
  LearningEntry,
  HumanReviewDecision,
  HumanReviewStatus,
  HumanReviewUrgency,
  HumanFeedback,
  HumanReviewItem,
  HumanReviewFilter,
  HumanReviewStats,
  QualityDimension,
  DimensionScore,
  QualityScore,
  QualityThreshold,
  SkillDimensionCriteria,
  SkillQualityCriteria,
} from "./types/index.ts";

// ── Type Constants ────────────────────────────────────────────────────────────
export {
  SQUAD_NAMES,
  SKILL_NAMES,
  FOUNDATION_SKILL,
  SKILL_SQUAD_MAP,
  getSquadSkills,
  PRIORITIES,
  PRIORITY_LABELS,
  TASK_STATUSES,
  VALID_TRANSITIONS,
  validateTransition,
  InvalidTransitionError,
  REVIEW_VERDICTS,
  PIPELINE_STATUSES,
  EVENT_TYPES,
  SYSTEM_STATES,
  DEGRADATION_LEVELS,
  DEGRADATION_DESCRIPTIONS,
  COMPONENT_STATUSES,
  WORKSPACE_DIRS,
  HUMAN_REVIEW_DECISIONS,
  HUMAN_REVIEW_STATUSES,
  HUMAN_REVIEW_URGENCIES,
  QUALITY_DIMENSIONS,
  DEFAULT_QUALITY_THRESHOLD,
} from "./types/index.ts";

// ── Workspace ─────────────────────────────────────────────────────────────────
export {
  WorkspaceError,
  type WorkspaceErrorCode,
  generateTaskId,
  generateReviewId,
  generateRunId,
  generateHumanReviewId,
  type FileLock,
  acquireLock,
  type ParsedMarkdown,
  parseFrontmatter,
  serializeTask,
  deserializeTask,
  serializeReview,
  deserializeReview,
  serializeLearningEntry,
  parseLearnings,
  serializeGoal,
  deserializeGoal,
  serializeGoalPlan,
  deserializeGoalPlan,
  serializeHumanReview,
  deserializeHumanReview,
  validateTask,
  validateReview,
  type WorkspaceManager,
  FileSystemWorkspaceManager,
  createWorkspacePaths,
} from "./workspace/index.ts";

// ── Agents ───────────────────────────────────────────────────────────────────
export {
  AGENT_DEPENDENCY_GRAPH,
  getUpstreamSkills,
  getDownstreamSkills,
  type PipelineTemplate,
  PIPELINE_TEMPLATES,
  loadSkillMeta,
  loadAllSkills,
  // Claude Client
  type ClaudeClient,
  type ClaudeMessageParams,
  type ClaudeMessage,
  type ClaudeMessageResult,
  type ExecutionErrorCode,
  ExecutionError,
  MODEL_MAP,
  COST_PER_MILLION_TOKENS,
  estimateCost,
  AnthropicClaudeClient,
  // Model Selector
  selectModelTier,
  // Prompt Builder
  type BuiltPrompt,
  buildAgentPrompt,
  // Agent Executor
  type ExecutorConfig,
  type ExecutionResult,
  type ExecutionMetadata,
  type ExecuteOptions,
  AgentExecutor,
  DEFAULT_EXECUTOR_CONFIG,
} from "./agents/index.ts";

// ── Director ─────────────────────────────────────────────────────────────────
export type {
  GoalCategory,
  Goal,
  GoalPhase,
  GoalPlan,
  SquadRoute,
  RoutingDecision,
  DirectorAction,
  DirectorDecision,
  EscalationReason,
  Escalation,
  BudgetLevel,
  BudgetState,
  DirectorConfig,
  SemanticReviewResult,
  QualityReviewResult,
} from "./director/index.ts";

export {
  GOAL_CATEGORIES,
  DIRECTOR_ACTIONS,
  ESCALATION_REASONS,
  BUDGET_LEVELS,
  DEFAULT_DIRECTOR_CONFIG,
  DIRECTOR_SYSTEM_PROMPT,
  routeGoal,
  selectSkills,
  ROUTING_RULES,
  GoalDecomposer,
  GOAL_CATEGORY_TEMPLATE_MAP,
  PipelineFactory,
  ReviewEngine,
  EscalationEngine,
  MarketingDirector,
  generateGoalId,
  HumanReviewManager,
  QualityScorer,
  DEFAULT_SKILL_CRITERIA,
  getSkillCriteria,
  resolveThreshold,
} from "./director/index.ts";

// ── Pipeline Engine ──────────────────────────────────────────────────────────
export {
  SequentialPipelineEngine,
  PipelineError,
  type PipelineEngineConfig,
  type StepResult,
  type PipelineResult,
  type PipelineErrorCode,
} from "./pipeline/index.ts";

// ── Queue ────────────────────────────────────────────────────────────────────
export type {
  RedisConfig,
  TaskQueueConfig,
  QueueRetryConfig,
  QueueJobData,
  QueueJobResult,
  RoutingAction,
  DeadLetterEntry,
  QueueHealth,
  QueueAddOptions,
  QueueAdapter,
  FailedJob,
  WorkerAdapter,
  JobHandle,
  ProcessorFn,
  BudgetDecision,
  WorkerProcessorDeps,
  TaskQueueManagerDeps,
  EnqueueResult,
  RedisClient,
  RedisConnectionManager,
} from "./queue/index.ts";

export {
  DEFAULT_REDIS_CONFIG,
  DEFAULT_QUEUE_RETRY,
  DEFAULT_TASK_QUEUE_CONFIG,
  BudgetDeferralError,
  CascadePauseError,
  TaskExecutionError,
  PRIORITY_MAP,
  taskPriorityToQueuePriority,
  queuePriorityToTaskPriority,
  BudgetGate,
  FailureTracker,
  FallbackQueue,
  createRedisConnection,
  createRedisConnectionFromClient,
  CompletionRouter,
  createWorkerProcessor,
  TaskQueueManager,
} from "./queue/index.ts";

// ── Events ──────────────────────────────────────────────────────────────────
export {
  EventBus,
  DEFAULT_EVENT_MAPPINGS,
  createWebhookServer,
} from "./events/index.ts";

export type {
  EventMapping,
  EventBusDeps,
  EventBusDirector,
  EventBusQueueManager,
  EventBusLogger,
  EmitResult,
  EventEmitter,
  WebhookEventBus,
  WebhookServerConfig,
  WebhookServer,
  WebhookStats,
} from "./events/index.ts";
