// ── Types ─────────────────────────────────────────────────────────────────────
export type {
  SquadName,
  SkillName,
  AgentMeta,
  ModelTier,
  AgentConfig,
  Priority,
  TaskStatus,
  TaskInput,
  TaskOutput,
  TaskNext,
  TaskFrom,
  Task,
  TaskFilter,
  ReviewVerdict,
  FindingSeverity,
  ReviewFinding,
  RevisionPriority,
  RevisionRequest,
  Review,
  PipelineStep,
  PipelineStatus,
  PipelineTrigger,
  PipelineDefinition,
  PipelineRun,
  EventType,
  SystemEvent,
  ScheduleEntry,
  SystemState,
  DegradationLevel,
  ComponentStatus,
  ComponentHealth,
  SystemHealth,
  WorkspaceDir,
  WorkspaceConfig,
  WorkspacePaths,
  LearningEntry,
} from "./types/index.ts";

// ── Type Constants ────────────────────────────────────────────────────────────
export {
  SQUAD_NAMES,
  SKILL_NAMES,
  FOUNDATION_SKILL,
  SKILL_SQUAD_MAP,
  getSquadSkills,
  PRIORITIES,
  PRIORITY_LABELS,
  TASK_STATUSES,
  REVIEW_VERDICTS,
  PIPELINE_STATUSES,
  EVENT_TYPES,
  SYSTEM_STATES,
  DEGRADATION_LEVELS,
  DEGRADATION_DESCRIPTIONS,
  COMPONENT_STATUSES,
  WORKSPACE_DIRS,
} from "./types/index.ts";

// ── Workspace ─────────────────────────────────────────────────────────────────
export {
  WorkspaceError,
  type WorkspaceErrorCode,
  generateTaskId,
  generateReviewId,
  generateRunId,
  type FileLock,
  acquireLock,
  type ParsedMarkdown,
  parseFrontmatter,
  serializeTask,
  deserializeTask,
  serializeReview,
  deserializeReview,
  serializeLearningEntry,
  validateTask,
  validateReview,
  type WorkspaceManager,
  FileSystemWorkspaceManager,
  createWorkspacePaths,
} from "./workspace/index.ts";

// ── Agents (Task 7 — new modular agent system) ──────────────────────────────
export {
  AGENT_DEPENDENCY_GRAPH,
  getUpstreamSkills,
  getDownstreamSkills,
  type PipelineTemplate,
  PIPELINE_TEMPLATES,
  loadSkillMeta,
  loadAllSkills,
  // Claude Client (new)
  type ClaudeClient as AgentClaudeClient,
  type ClaudeMessageParams,
  type ClaudeMessage,
  type ClaudeMessageResult,
  type ExecutionErrorCode as AgentExecutionErrorCode,
  ExecutionError as AgentExecutionError,
  MODEL_MAP,
  COST_PER_MILLION_TOKENS,
  estimateCost,
  AnthropicClaudeClient,
  // Model Selector
  selectModelTier,
  // Prompt Builder
  type BuiltPrompt,
  buildAgentPrompt,
  // Agent Executor (new)
  type ExecutorConfig as AgentExecutorConfig,
  type ExecutionResult as AgentExecutionResult,
  type ExecutionMetadata,
  AgentExecutor as ModularAgentExecutor,
  DEFAULT_EXECUTOR_CONFIG,
} from "./agents/index.ts";

// ── Executor (Tasks 1-6 — used by pipeline and queue) ──────────────────────
export {
  AgentExecutor,
  AnthropicClaudeClient as LegacyAnthropicClaudeClient,
  MockClaudeClient,
  loadSkillContent,
  buildPrompt,
  cancellableSleep,
  ExecutionError,
  DEFAULT_MODEL_MAP,
  createDefaultConfig,
  type ClaudeClient,
  type ClaudeClientConfig,
  type ClaudeRequest,
  type ClaudeResponse,
  type ExecutionResult,
  type ExecutionStatus,
  type ExecutorConfig,
  type ExecutionErrorCode,
  type SkillContent,
  type BuildPromptParams,
  type UpstreamOutput,
} from "./executor/index.ts";

// ── Director ─────────────────────────────────────────────────────────────────
export type {
  GoalCategory,
  Goal,
  GoalPhase,
  GoalPlan,
  SquadRoute,
  RoutingDecision,
  DirectorAction,
  DirectorDecision,
  EscalationReason,
  Escalation,
  BudgetLevel,
  BudgetState,
  DirectorConfig,
  SemanticReviewResult,
} from "./director/index.ts";

export {
  GOAL_CATEGORIES,
  DIRECTOR_ACTIONS,
  ESCALATION_REASONS,
  BUDGET_LEVELS,
  DEFAULT_DIRECTOR_CONFIG,
  DIRECTOR_SYSTEM_PROMPT,
  routeGoal,
  selectSkills,
  ROUTING_RULES,
  GoalDecomposer,
  GOAL_CATEGORY_TEMPLATE_MAP,
  PipelineFactory,
  ReviewEngine,
  EscalationEngine,
  MarketingDirector,
  generateGoalId,
} from "./director/index.ts";

// ── Pipeline Engine ──────────────────────────────────────────────────────────
export {
  SequentialPipelineEngine,
  PipelineError,
  type PipelineEngineConfig,
  type StepResult,
  type PipelineResult,
  type PipelineErrorCode,
} from "./pipeline/index.ts";

// ── Queue ────────────────────────────────────────────────────────────────────
export type {
  RedisConfig,
  TaskQueueConfig,
  QueueRetryConfig,
  QueueJobData,
  QueueJobResult,
  RoutingAction,
  DeadLetterEntry,
  QueueHealth,
  QueueAddOptions,
  QueueAdapter,
  FailedJob,
  WorkerAdapter,
  JobHandle,
  ProcessorFn,
  BudgetDecision,
  WorkerProcessorDeps,
  TaskQueueManagerDeps,
  EnqueueResult,
  RedisClient,
  RedisConnectionManager,
} from "./queue/index.ts";

export {
  DEFAULT_REDIS_CONFIG,
  DEFAULT_QUEUE_RETRY,
  DEFAULT_TASK_QUEUE_CONFIG,
  BudgetDeferralError,
  CascadePauseError,
  TaskExecutionError,
  PRIORITY_MAP,
  taskPriorityToQueuePriority,
  queuePriorityToTaskPriority,
  BudgetGate,
  FailureTracker,
  FallbackQueue,
  createRedisConnection,
  createRedisConnectionFromClient,
  CompletionRouter,
  createWorkerProcessor,
  TaskQueueManager,
} from "./queue/index.ts";
